mpi:
  - openmpi    # [osx and x86_64]
  - mpich      # [linux]
  - nompi

MACOSX_SDK_VERSION:      # [osx and x86_64]
  - '10.13'              # [osx and x86_64]

c_stdlib_version:          # [osx and x86_64]
  - '10.13'                # [osx and x86_64]