{% set name = "faunus" %}
{% set version = "2.3.0" %}
{% set sha256 = "09bb68560e2889cf564801bcd600e434a1779db4da8872dbe6b2741009b9c759" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/mlund/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win or py<36]
  script:
    - unset _CONDA_PYTHON_SYSCONFIGDATA_NAME  # [linux]
    - cmake -DVERSION_STRING=v{{ version }} -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX  # [mpi == 'nompi']
    - cmake -DENABLE_MPI=on -DVERSION_STRING=v{{ version }} -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX  # [mpi != 'nompi']
    - make
    - make install

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.11.4
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - pandoc 2.2.1
    - pypandoc 1.4
    - beautifulsoup4 4.8.*
    - ruamel_yaml 0.15.*
    - jinja2
    - sdl2
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - ruamel_yaml >=0.15
    - beautifulsoup4 4.8.*
    - pygments >=2.2
    - jinja2

test:
  commands:
    - test -x $PREFIX/bin/faunus
    - $PREFIX/bin/faunus --version
  imports:
    - pyfaunus

about:
  home: https://github.com/mlund/faunus
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Framework for Molecular Monte Carlo Simulations'
  description: |
      Faunus is a framework for molecular simulations using Metropolis
      Monte Carlo techniques. It is written in C++14 and has experimental
      support for python bindings.
  doc_url: https://faunus.readthedocs.io
  dev_url: https://github.com/mlund/faunus

extra:
  recipe-maintainers:
    - mlund
