{% set name = "faunus" %}
{% set version = "2.4.0" %}
{% set sha256 = "14b5628a6a05857a809d9ef56b97d0c67db9923e26683a69e65384fa7eaaa07a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/mlund/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
      - azurefix.patch

build:
  number: 1
  skip: True  # [win or py<36 or linux or osx]
  script:
    - unset _CONDA_PYTHON_SYSCONFIGDATA_NAME  # [linux or ppc64le]
    - cmake -DVERSION_STRING=v{{ version }} -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX  # [mpi == 'nompi']
    - cmake -DENABLE_MPI=on -DVERSION_STRING=v{{ version }} -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX  # [mpi != 'nompi']
    - make faunus pyfaunus
    - make install

requirements:
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.11.4
  host:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - pandoc 2.2.1  # [x86_64 or osx]
    - pypandoc 1.4  # [x86_64 or osx]
    - beautifulsoup4 4.8.*  # [x86_64 or osx]
    - ruamel_yaml 0.15.*
    - jinja2  # [x86_64 or osx]
    - sdl2  # [x86_64 or osx]
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - python
    - ruamel_yaml >=0.15
    - pygments >=2.2  # [x86_64 or osx]
    - jinja2  # [x86_64 or osx]
    - jsonschema >=3

test:
  commands:
    - test -x $PREFIX/bin/faunus
    - $PREFIX/bin/faunus --version
  imports:
    - pyfaunus

about:
  home: https://github.com/mlund/faunus
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Framework for Molecular Monte Carlo Simulations'
  description: |
      Faunus is a framework for molecular simulations using Metropolis
      Monte Carlo techniques. It is written in C++17 and has experimental
      support for python bindings.
  doc_url: https://faunus.readthedocs.io
  dev_url: https://github.com/mlund/faunus

extra:
  recipe-maintainers:
    - mlund
