# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FI0dAKERgj9qgOrVLkpBQEzdAVF1bia5DYzGEpAOFEWOeD9y5tp6dDGsqSHnu4WI+gNzmk+U10xFKGeEDCfaO0f7z0s9dSkEgU2cNpZKyfUWHc/a2k/HN0ymPLY7+wYkC6VqlUiLMmHq7A7ZQh0UC44eqKP+s4uCZAOBsyh6ACmYYG0ETpj2Gd7bJdHO35+Ob2naFmDi3m88G1sjIjT1s+CNXnnFI61jJU5gz37eN/VIQIzPz1nb2u6mkYiF9Dw4EnlYJXw8fA77diqJnNKYzbpv9RqsaItbRfeXLyTxtvVbim1Msj4k1bwZKJMp03vNMjnhLA5ORv8WIFSJtna5z+AGNh6ORFFgwhP17BVU4EMYtxg1AHwNAo0ten86aacrIm3cD2LCe9sZhQ6kEKyuFUo0R/eP5p7ljNX69hNXudi7qOovzuMPIe5NjsZN9vQIOmiDwcg1CcApWSX3ZObL1+CbmlGUx4A9vegB6VpnPnwpsSOBc+xvlESr+PZ/J4puXdNL55u8Lv5xfGBy+l0+Zyn3iQQ5hZ/dYkJx9J20e9y2vJl/0XLAwKLbj9VijxpiButc9vE7pJsh5TFI4nmuvJ44v9lyj5xNBTHMXjYHd7f0EJDOWAW5s6jYa9gMYz7CCmG5GgJ+lZBWI5/W8rYc3MCLTlsJEbAkHT5ljuQZAJE="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_mpimpichpython3.6.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpimpichpython3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpinompipython3.6.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpinompipython3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpiopenmpipython3.6.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

    - env: CONFIG=linux_ppc64le_mpiopenmpipython3.7.____cpython UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi