travis:
  secure:
    BINSTAR_TOKEN: FI0dAKERgj9qgOrVLkpBQEzdAVF1bia5DYzGEpAOFEWOeD9y5tp6dDGsqSHnu4WI+gNzmk+U10xFKGeEDCfaO0f7z0s9dSkEgU2cNpZKyfUWHc/a2k/HN0ymPLY7+wYkC6VqlUiLMmHq7A7ZQh0UC44eqKP+s4uCZAOBsyh6ACmYYG0ETpj2Gd7bJdHO35+Ob2naFmDi3m88G1sjIjT1s+CNXnnFI61jJU5gz37eN/VIQIzPz1nb2u6mkYiF9Dw4EnlYJXw8fA77diqJnNKYzbpv9RqsaItbRfeXLyTxtvVbim1Msj4k1bwZKJMp03vNMjnhLA5ORv8WIFSJtna5z+AGNh6ORFFgwhP17BVU4EMYtxg1AHwNAo0ten86aacrIm3cD2LCe9sZhQ6kEKyuFUo0R/eP5p7ljNX69hNXudi7qOovzuMPIe5NjsZN9vQIOmiDwcg1CcApWSX3ZObL1+CbmlGUx4A9vegB6VpnPnwpsSOBc+xvlESr+PZ/J4puXdNL55u8Lv5xfGBy+l0+Zyn3iQQ5hZ/dYkJx9J20e9y2vJl/0XLAwKLbj9VijxpiButc9vE7pJsh5TFI4nmuvJ44v9lyj5xNBTHMXjYHd7f0EJDOWAW5s6jYa9gMYz7CCmG5GgJ+lZBWI5/W8rYc3MCLTlsJEbAkHT5ljuQZAJE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
